sudo:
  false

language:
  php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

cache:
  directories:
    - vendor

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover --colors

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
